### PR TITLE
Replace `resizeToFitChildrenWithOption` with `fixGeometryWithOptions`

### PR DESCRIPTION
**Pull request by yuanqing**
Fixes https://github.com/pberrecloth/butter-sketch-plugin/issues/22

### CODE REVIEW

**Comment by adiron** [comment]
Works for me  :)

**Comment by golevkadesign** [comment]
It works for me! thanks a lot!

**Comment by eeklipzz** [comment]
I'm not really sure how to work with GitHub's pull request mechanism. I was able to find butter.js and manually replace all the ones with the others. That fixed the group spacing problem. But, my cursor isn't positioning into the input field like it was previously. In the past, I'd select one of the options and then it'd put the cursor in the input field immediately so all I had to do was start typing the amount to space by. Now, I have the added step of having to click the mouse over the input field to position the cursor. A bit of a speed bump for me.

**Comment by yuanqing** [comment]
> But, my cursor isn't positioning into the input field like it was previously. In the past, I'd select one of the options and then it'd put the cursor in the input field immediately so all I had to do was start typing the amount to space by. Now, I have the added step of having to click the mouse over the input field to position the cursor. A bit of a speed bump for me.

Unfortunately it looks like this behaviour is broken across _all_ plugins (not just Butter) as of Sketch 53.

For now this PR only fixes the auto-spacing functionality of Butter.

**Pull request merged**
